name: Pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install openfold
        run: uv pip install --no-deps git+https://github.com/amyxlu/openfold.git --no-build-isolation

      - name: Run tests
        run: uv run pytest